export function isArray(data: any): boolean;
export function isObject(data: any): boolean;
export function isObjectStrict(data: any): boolean;
export function isBuffer(data: any): boolean;
export function isString(data: any): boolean;
export function isFunction(data: any): boolean;
export function isEncryptable(data: any): boolean;
export function isNumber(data: any): boolean;
export function isBoolean(data: any): boolean;
export function getHeaderType(data: any): "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function" | "array";
export function isDefined(data: any): boolean;
export function isUndefined(data: any): boolean;
export function ensureString(data: any): any;
export function base64ToBuffer(data: any): Buffer;
export function utf8ToBase64Url(data: any): any;
export function formatKey(key: any): any;
