name: Run Node.js SDK E2E Tests

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!main'

jobs:
  run-tests:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24, 26]
        os: [ubuntu-latest]
        include:
          - perform-attestation: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test:e2e
        env:
          EV_APP_UUID: ${{ secrets.EV_APP_UUID_V5 }}
          EV_API_KEY: ${{ secrets.EV_API_KEY_V5 }}
          EV_FUNCTION_NAME: ${{ secrets.EV_FUNCTION_NAME_V5 }}
          EV_INITIALIZATION_ERROR_FUNCTION_NAME: ${{ secrets.EV_INITIALIZATION_ERROR_FUNCTION_NAME }}
          EV_SYNTHETIC_ENDPOINT_URL: ${{ secrets.EV_SYNTHETIC_ENDPOINT_URL }}
